CREATE TABLE request_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE service_requests (
    id uuid PRIMARY KEY,
    request_number varchar(32) NOT NULL UNIQUE,
    title varchar(120) NOT NULL,
    description varchar(4000) NOT NULL,
    category_id integer NOT NULL REFERENCES request_categories(id),
    status integer NOT NULL,
    priority integer NOT NULL,
    submitted_by_id text NOT NULL,
    assigned_to_id text NULL,
    version bigint NOT NULL DEFAULT 1,
    created_at_utc timestamptz NOT NULL,
    updated_at_utc timestamptz NOT NULL
);

CREATE TABLE request_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id uuid NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    action_type varchar(80) NOT NULL,
    from_status integer NULL,
    to_status integer NULL,
    notes varchar(2000) NULL,
    performed_by_id text NOT NULL,
    performed_at_utc timestamptz NOT NULL
);

CREATE TABLE request_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id uuid NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    message varchar(2000) NOT NULL,
    recipient_user_id text NOT NULL,
    created_at_utc timestamptz NOT NULL,
    is_read boolean NOT NULL DEFAULT false
);
